[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  # Netlify's default behavior is to use `next build` under the hood,
  # so you do not need to specify the build command manually unless you have a custom one.
