[build]
  command = "npm run build"
  publish = ".next"  # Default build folder for Next.js

  [build.environment]
    NODE_ENV = "production"

  [[plugins]]
    package = "@netlify/plugin-nextjs"

  [build.cache]
    directories = ["node_modules", ".next/cache"]
